dashboard/urls.py
from django.conf.urls import url
from . import views

from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^main/', views.MainView.as_view(), name="main"),
    url(r'^$', RedirectView.as_view(url='main/', permanent=False)),
]

datastore_proxy/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^project_blocks/$', views.ProjectBlockListProxyView.as_view(), name="project_block_list"),
	url(r'^project_blocks/(?P<pk>[0-9]+)/$', views.ProjectBlockDetailProxyView.as_view(), name="project_block_detail"),

	url(r'^projects/$', views.ProjectListProxyView.as_view(), name="project_list"),
	url(r'^projects/(?P<pk>[0-9]+)/$', views.ProjectDetailProxyView.as_view(), name="project_detail"),

	url(r'^meter_runs/', views.MeterRunListProxyView.as_view(), name='meter_run_list'),
	url(r'^meter_runs/(?P<pk>[0-9]+)/', views.MeterRunDetailProxyView.as_view(), name='meter_run_detail'),

	url(r'^project_attributes/', views.ProjectAttributeListProxyView.as_view(), name='project_attribute_list'),
	url(r'^project_attributes/(?P<pk>[0-9]+)/', views.ProjectAttributeDetailProxyView.as_view(), name='project_attribute_detail'),

	url(r'^project_attribute_keys/', views.ProjectAttributeKeyListProxyView.as_view(), name='project_attribute_key_list'),
	url(r'^project_attribute_keys/(?P<pk>[0-9]+)/', views.ProjectAttributeKeyDetailProxyView.as_view(), name='project_attribute_key_detail'),

	url(r'^consumption_metadatas/', views.ConsumptionMetadataListProxyView.as_view(), name='consumption_metadata_list'),
	url(r'^consumption_metadatas/(?P<pk>[0-9]+)/', views.ConsumptionMetadataDetailProxyView.as_view(), name='consumption_metadata_detail'),
]

oeem_client/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^datastore_proxy/', include('datastore_proxy.urls', namespace='datastore_proxy')),

    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=False), name='index'),

    url(r'^accounts/login/$', login, {'template_name':'admin/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

dashboard/views.py
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse

from oeem_client import settings

class MainView(TemplateView):

    template_name = "dashboard/main.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MainView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)

        context['project_block_list_url'] = reverse('datastore_proxy:project_block_list')
        context['project_list_url'] = reverse('datastore_proxy:project_list')
        context['meter_run_list_url'] = reverse('datastore_proxy:meter_run_list')
        context['project_attribute_key_list_url'] = reverse('datastore_proxy:project_attribute_key_list')
        context['project_attribute_list_url'] = reverse('datastore_proxy:project_attribute_list')
        context['consumption_metadata_list_url'] = reverse('datastore_proxy:consumption_metadata_list')
        context['logo'] = 'client_logos/'+ settings.CLIENT_SETTINGS['logo']

        return context

datastore_proxy/views.py
from rest_framework_proxy.views import ProxyView

from django.conf import settings

class DatastoreMixin(object):

    proxy_host = settings.DATASTORE_URL

    def get_headers(self, request):
        headers = self.get_default_headers(request)

        # Translate Accept HTTP field
        accept_maps = self.proxy_settings.ACCEPT_MAPS
        for old, new in accept_maps.items():
            headers['Accept'] = headers['Accept'].replace(old, new)

        headers['Authorization'] = "Bearer {}".format(settings.DATASTORE_ACCESS_TOKEN)
        return headers


class ProjectBlockListProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/project_blocks/"

class ProjectBlockDetailProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/project_blocks/%(pk)s/"


class ProjectListProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/projects/"

class ProjectDetailProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/projects/%(pk)s/"


class MeterRunListProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/meter_runs/"

class MeterRunDetailProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/meter_runs/%(pk)s/"


class ProjectAttributeKeyListProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/project_attribute_keys/"

class ProjectAttributeKeyDetailProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/project_attribute_keys/%(pk)s/"


class ProjectAttributeListProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/project_attributes/"

class ProjectAttributeDetailProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/project_attributes/%(pk)s/"


class ConsumptionMetadataListProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/consumption_metadatas/"

class ConsumptionMetadataDetailProxyView(DatastoreMixin, ProxyView):
    source = "api/v1/consumption_metadatas/%(pk)s/"

dashboard/templates/dashboard/base.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{% endblock %}

{% block body %}

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

{% block content %}
{% endblock %}

<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

{% block extrajs %}
{% endblock %}

{% endblock %}

dashboard/templates/dashboard/detail_view.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}

{% load humanize %}

{% block title %}Project Block Detail{% endblock %}

{% block content %}

  <div class="container-fluid project-block-summary">
    <div class="row-fluid">

      <div class="col-xs-7 no-padding">
        <div class="row-fluid" id="project-block-header">
          <div class="logo">
            <a href="/">
              <img src="{% static logo %}">
            </a>
          </div>
          <div id="project-block-title">
            <h2 class="title">{{ project_block.name }}</h2>
          </div>
        </div>

        <div class="row-fluid" id="project-block-content">
          <div class="col-xs-2">
            <h5>Total Projects</h5>
            <h2 id="count-projects-all">{{ project_block.n_projects }}</h2>
          </div>

          {% for savings_data in all_savings_data %}
          <div class="energy-detail-pane" id="pane-summary-{{ savings_data.energy_type_slug }}">

            <div class="col-xs-5">
              <h5>Total Gross Savings</h5>
              <h2 id="total-gross-savings">{{ savings_data.total_gross_savings | floatformat:"0" | intcomma }}
              {{ savings_data.unit }}</h2>
            </div>

            <div class="col-xs-5">
              <h5>Total Annual Savings</h5>
              <h2 id="total-annual-savings">{{ savings_data.total_annual_savings | floatformat:"0" | intcomma }}
              {{ savings_data.unit }}/year</h2>
            </div>

          </div>
          {% endfor %}

        </div>

        <div class="row-fluid" id="energy-pane-menu">
          <div class="col-xs-12">
            <div>
              {% for savings_data in all_savings_data %}
              <a href="javascript://" class="energy-pane-select"
                target-pane="#pane-{{ savings_data.energy_type_slug }}, #pane-summary-{{ savings_data.energy_type_slug }}">
                <i class="fa {{ savings_data.icon }} fa-lg"></i> {{ savings_data.energy_type }}
              </a>
              {% endfor %}
            </div>
          </div>
        </div>

      </div>


      <div id="col-xs-5 no-padding">
        <div id="map"></div>
      </div>
    </div>
  </div>

  {% for savings_data in all_savings_data %}
    <div class="energy-pane" id="pane-{{ savings_data.energy_type_slug }}">
      {% include "partials/utility_pane.html" %}
    </div>
  {% endfor %}

{% endblock %}

{% block extrajs %}
<script type="text/javascript">

$(document).ready(function () {

  // ****************** MAP ***************
  // create map
  var map = L.map('map', {scrollWheelZoom:false}).setView([{{ map_data.center_lat }},{{ map_data.center_long }}], {{ map_data.zoom }});
  L.tileLayer(
      'https://{s}.tiles.mapbox.com/v3/cathyd125.k6ock5a1/{z}/{x}/{y}.png',
      {
        attribution: '<a href="http://openstreetmap.org">OpenStreetMap</a>,'+
          ' <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'+' | <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18
      })
    .addTo(map);

  // adding dots to map
  var locations = {{ map_data.latlongs | safe}};
  for (var i = 0; i < locations.length; i++) {
    jitterx = (Math.random() - .5)/50;
    jittery = (Math.random() - .5)/50;
    marker = new L.circleMarker(
          [locations[i][0] + jitterx,locations[i][1] + jittery],
          {color: "#00b16a"})
      .setRadius(1)
      .addTo(map);
  }

  // ********* PAGE NAVIGATION ************
  // show first energy type on page load
  $('.energy-pane').hide()
  $('.energy-pane').first().show()
  $('.energy-detail-pane').hide()
  $('.energy-detail-pane').first().show()
  $('.energy-pane-select').first().addClass('selected')

  // switch energy panes from menus
  $('.energy-pane-select').on('click', function(e){
    $('.energy-pane').hide()
    $('.energy-detail-pane').hide()
    $(this.getAttribute("target-pane")).show()

    $('.energy-pane-select').removeClass('selected')
    $(this).addClass('selected')
  });



  // ************* OLD JS *******************
  // TO-DO: REORGANIZE EVERYTHING BELOW INTO TEMPLATE TAGS

  {# BaselineTimeseriesHelper.create('baseline-timeseries', #}
  {#     'Total Energy Usage Over Time', #}
  {#     'Energy Usage (kWh)', #}
  {#     baseline_data.xlabels[0], #}
  {#     baseline_data.actual_start_idx, #}
  {#     baseline_data.series_baseline, #}
  {#     baseline_data.series_actual); #}
  {#  #}
  {# //Electricity #}
  {#  #}
  {# $('.elec-sum-gross').html(commaSeparateNumber(elec_data.savings_sums.gross_actual)); #}
  {# $('#elec-sum-gross-pred').html(commaSeparateNumber(elec_data.savings_sums.gross_pred)); #}
  {# $('#elec-portfolio-rr').html(commaSeparateNumber(elec_data.savings_sums.portfolio_rr)); #}
  {#  #}
  {# elec_data.rr_histogram.dataseries.color = "#1186BB"; #}
  {#  #}
  {# TimeseriesHelper.create("elec_rr_timeseries", #}
  {#     "Average Electricity Realization Rate", #}
  {#     "Average Realization Rate", #}
  {#     "Retrofit End Date", #}
  {#     elec_data.rr_timeseries.xlabels, #}
  {#     elec_data.rr_timeseries.rr, #}
  {#     elec_data.rr_timeseries.errors); #}
  {#  #}
  {# HistHelper.create("elec_rr_hist", #}
  {#     "Distribution of Electricity Realization Rates", #}
  {#     "Projects", #}
  {#     "Realization Rate", #}
  {#     elec_data.rr_histogram.xlabels, #}
  {#     [elec_data.rr_histogram.dataseries]); #}
  {#  #}
  {# ScatterHelper.create("elec_savings_scatter", #}
  {#     "Yearly Electricity Savings: Actual vs. Predicted", #}
  {#     "Yearly Weather Normalized Savings (kWh)", #}
  {#     "Predicted Yearly Savings (kWh)", #}
  {#     elec_data.savings_scatter.dataseries, #}
  {#     elec_data.savings_scatter.plotmax); #}
  {#  #}
  {# $('.gas-sum-gross').html(commaSeparateNumber(gas_data.savings_sums.gross_actual)); #}
  {# $('#gas-sum-gross-pred').html(commaSeparateNumber(gas_data.savings_sums.gross_pred)); #}
  {# $('#gas-portfolio-rr').html(commaSeparateNumber(gas_data.savings_sums.portfolio_rr)); #}
  {#  #}
  {# gas_data.rr_histogram.dataseries.color = "#1186BB"; #}
  {#  #}
  {# TimeseriesHelper.create("gas_rr_timeseries", #}
  {#     "Average Gas Realization Rate", #}
  {#     "Average Realization Rate", #}
  {#     "Retrofit End Date", #}
  {#     gas_data.rr_timeseries.xlabels, #}
  {#     gas_data.rr_timeseries.rr, #}
  {#     gas_data.rr_timeseries.errors); #}
  {#  #}
  {# HistHelper.create("gas_rr_hist", #}
  {#     "Distribution of Gas Realization Rates", #}
  {#     "Projects", #}
  {#     "Realization Rate", #}
  {#     gas_data.rr_histogram.xlabels, #}
  {#     [gas_data.rr_histogram.dataseries]); #}
  {#  #}
  {# ScatterHelper.create("gas_savings_scatter", #}
  {#     "Yearly Gas Savings: Actual vs. Predicted", #}
  {#     "Yearly Weather Normalized Savings (therm)", #}
  {#     "Predicted Yearly Savings (therm)", #}
  {#     gas_data.savings_scatter.dataseries, #}
  {#     gas_data.savings_scatter.plotmax); #}

});
</script>


{% endblock %}

dashboard/templates/dashboard/index_view.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}

{% block title %}Project Block Index{% endblock %}

{% block content %}
<div class="row-fluid">
  <div class="col-sm-12" id="project-block-header">
    <div class="logo">
      <img src="{% static logo %}">
    </div>
    <h2 class="title">{{client_name}} - Project Block Index</h2>
  </div>
</div>

<div class="container">
  <div class="row-fluid">
    <div class="col-sm-8 col-sm-offset-2">
      <h2>Project Blocks</h2>
      <ul>
        {% for project_block in project_blocks %}
        <li><a href="{% url 'dashboard:project_block_detail' client_slug project_block.id %}">{{ project_block.name }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

dashboard/templates/dashboard/main.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}

{% block title %}Dashboard{% endblock %}

{% block content %}


<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">

  <!-- this is the horizontal bar at the top -->
<!--   <header class="mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Home</span>
      <div class="mdl-layout-spacer"></div>
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
        <i class="material-icons">more_vert</i>
      </button>
      <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
        <li class="mdl-menu__item">Item</li>
        <li class="mdl-menu__item">Item</li>
        <li class="mdl-menu__item">Item</li>
      </ul>
    </div>
  </header> -->

  <!-- this is the vertical nav on the left -->
  <div id="oeem-sidebar" class="mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
    <header>
      <a class="logo" href="{% url 'dashboard:main' %}">
        <img alt="OEE" src="{% static logo %}">
      </a>
    </header>
    <nav class="mdl-navigation mdl-color--blue-grey-800">

      {% if user.is_staff %}
      <a class="mdl-navigation__link" href="{% url 'admin:index' %}" title="Admin">
        <i class="fa fa-cogs fa-lg"></i>
      </a>
      {% endif %}
      <a class="mdl-navigation__link" href="{% url 'logout' %}" title="Sign out">
        <i class="fa fa-sign-out fa-lg"></i>
      </a>

    </nav>
  </div>
  <main class="mdl-layout__content mdl-color--grey-100">


    <div id="oeem-content"></div>


  </main>
</div>

<script src="https://code.getmdl.io/1.1.3/material.min.js"></script>



{% endblock content %}

{% block extrajs %}


<script type="text/javascript">
document.csrf_token = "{{ csrf_token }}";
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.0.1/spin.min.js'></script>
<script src="{% static 'js/d3.tip.v0.6.3.js' %}"></script>
<script src="{% static 'dashboard/js/build/main.js' %}"></script>


{% endblock extrajs %}

dashboard/templates/partials/quick_stats.html
{% load humanize %}
<div class="col-xs-12">
  <h4>Quick Stats - {{savings_data.energy_type}}</h4>
</div>

<div class="col-xs-6">
  <h5 class="no-pad-bottom">
    <span data-toggle="popover" data-placement="top" data-content="placeholder explanation of where the annual usage numbers come from">
      <strong>Annual Usage</strong>
      <span class="muted">{{savings_data.unit}}/yr</span>
    </span>
  </h5>
  <div id="usage-bar-{{savings_data.energy_type_slug}}">
  </div>
  <script type="text/javascript">

    $(document).ready(function () {

      BarHelper.create('usage-bar-{{savings_data.energy_type_slug}}', {{ savings_data.total_annual_usage.baseline }}, {{savings_data.total_annual_usage.reporting}})
    });

  </script>
</div>

<div class="col-xs-6">
  <h5 class="no-pad-bottom">
    <span data-toggle="popover" data-placement="top" data-content="placeholder explanation of where the annual savings number comes from">
      <strong>Annual Savings</strong>
      <span class="muted">{{savings_data.unit}}/yr</span>
    </span>
  </h5>
  <h2 id="total-annual-savings">
    {{ savings_data.total_annual_savings | floatformat:"0" | intcomma }}
    {% if savings_data.total_annual_usage.percent_savings >= 0 %}
      <span class="badge-pct badge-success">{{savings_data.total_annual_usage.percent_savings}}%</span>
    {% else %}
      <span class="badge-pct badge-danger">{{savings_data.total_annual_usage.percent_savings}}%</span>
    {% endif %}
  </h2>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.blue_grey-blue.min.css" /> 
	<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/ol.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/daterangepicker.css' %}">
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
	<script src='{% static 'js/ol.js'%}'></script>

	<title>{% block title %}{% endblock %}</title>

</head>

<body>
{% block body %}
{% endblock %}
</body>



</html>